[package]
name = "zenth_database_local"
version = "0.1.0"
edition = "2024"

[dependencies]
zenth_crypto = { git = "https://github.com/ZenthProject/zenth_crypto.git" }
zenth_utils = { git = "https://github.com/ZenthProject/zenth_utils.git" }
rusqlite_migration = "2.2.0"
rusqlite = { version = "0.36", features = ["bundled-sqlcipher-vendored-openssl"] }
thiserror = "2.0.20"
zeroize = "1.9.0"
rand = "0.10.2"
hex = "0.4.3"
rang = "0.1.1"
